Fix S3 path-style option
inpsyde/backwpup pull request #119
Opened 2021-10-20 10:23 UTC by mattn

Update #57, #60, #81

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

**What is the current behavior?** (You can also link to an open issue here)

Path style is not saved eventhough check the option since HTML is broken. Also path style option is not enabled to the S3 APIs.

**What is the new behavior (if this is a feature change)?**

Use using `use_path_style_endpoint` for S3 API.
Path style is not saved eventhough check the option. Also path style option is not enabled to the S3 APIs.

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Now worked this plugin for S3 compatible servers. I checked this fix on minio, and Oracle Cloud.

**Other information**:

2021-11-06 09:50 UTC, mattn commented
@Dinamiko Could you please look this?

2021-11-29 14:22 UTC, devbanana requested changes
Thanks for the PR. Just some minor things.

2021-11-29 14:22 UTC, devbanana commented on inc/class-destination-s3.php
> +                                            ) ? 'checked="checked"' : '' ?>>
This should use the [checked()](https://developer.wordpress.org/reference/functions/checked/) WordPress function instead of using a manual ternary.

2021-11-29 14:22 UTC, devbanana commented on inc/class-destination-s3.php
> +                                                   ) ? 'checked="checked"' : '' ?>>
Same as above, should use [checked()](https://developer.wordpress.org/reference/functions/checked/)

2021-11-29 14:22 UTC, devbanana commented on inc/class-destination-s3.php
> +						s3base_region          : $( 'input[name="s3base_region"]' ).val(),
I'd actually rather not align the colons, but I know this is how it already was in the source code, so I'll fix this in the next version.

2021-11-29 14:22 UTC, devbanana commented on inc/class-s3-destination.php
> +                ],
What's the point of adding this custom destination? A custom destination is already supported in the `::fromJobId()` method ([line 207+](https://github.com/inpsyde/backwpup/blob/4ea1f40efcc7d875214952838a34ca3d0fd5deb6/inc/class-s3-destination.php#L207)).

2021-11-29 15:20 UTC, mattn commented
Thanks. Updated.

2021-12-21 04:02 UTC, mattn commented
Could you please take a look?

2022-03-13 13:11 UTC, mattn commented
ping @devbanana

2022-05-13 08:23 UTC, mattn commented
ping @danielhuesken

2022-05-24 12:09 UTC, devbanana approved these changes

2022-05-24 12:09 UTC, merged